#!/bin/sh
set -e

# Automatically added by dh_installinit/11.5.4
if [ "$1" = "purge" ] ; then
	update-rc.d gpm remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.5.4
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


if [ "$1" = "purge" ]; then
  echo " Removing gpm config file."
  rm -f /etc/gpm.conf
  if [ -x "/usr/bin/ucf" ]; then
    ucf --purge /etc/gpm.conf
  fi
fi

exit 0

